Dockerfile, package.json, src/index.ts
- Remove a second install from docker build
- Copy the schema file on build to dist
- Allow introspection always
@HedvigInsurance/clients
=> Oneline fixes

src/index.ts
- We now log out the inner errors in the graphql error
=> Log responsibly

src/api/index.ts, src/features/offer/sign.ts
This enables us to complete the signing flow client-side.
=> Add missing sign status fields

src/config.ts, src/resolvers/gifs.ts, src/resolvers/index.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
=> Add support for fetching gifs from giphy

src/api/index.ts, src/features/insurance/index.ts, src/resolvers/index.ts, src/resolvers/member.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
- New root query: member
- Added postal number to insurance
=> Expose member info needed for offer page

src/resolvers/file.ts
`memberId` should have been `memberid` 🙅‍♂️
=> fix mistake 🙈

src/api/index.ts, src/resolvers/cashbackOptions.ts, src/resolvers/index.ts, src/resolvers/selectCashbackOption.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
Makes it possible to set and get all charities
=> Add selectCashbackOptions and cashbackOptions

src/api/index.ts, src/resolvers/index.ts, src/resolvers/offerClosed.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
This triggers hedvig to send a message when the offer in app is closed. Needed to remove local schema from app.
=> Add offerClosed mutation

package.json, src/config.ts, src/context.ts, src/index.ts, src/middlewares/sentry.ts, src/schema.ts, src/utils/graphql-error.ts, yarn.lock
Sometimes you make me a little disappointed, apollo.
=> Log errors for both regular and subscription errors. and sentry.

package.json, src/schema.ts, yarn.lock
So when they 💩we still are alive and kicking 🔥
=> Cache GraphCMS

src/resolvers/cashback.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
This broke stuff, I should have anticipated that, rolling back until we get the new release out.
=> Revert "Make cashback nullable"

src/resolvers/cashback.ts
Reverts HedvigInsurance/giraffe#176
=> Revert "Fix cashback being null"

src/resolvers/cashback.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
Reverts HedvigInsurance/giraffe#174
=> Revert "Revert "Make cashback nullable""

.gitignore, src/api/index.ts, src/features/insurance/index.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
This PR adds the `livingSpace` field to `Insurance`.
=> Add livingSpace field to insurance

src/api/index.ts
Purpose: get a predictable date format to make parsing easier on frontend
=> Strip milliseconds from activeFrom date

bin/docker_push.sh, src/features/chat/transform.ts, src/resolvers/index.ts, src/resolvers/messages.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
Reflecting the new redis publishing from this pr: https://github.com/HedvigInsurance/bot-service/pull/145
=> Change messages subscriptions

src/api/index.ts, src/features/chat/transform.ts, src/resolvers/index.ts, src/resolvers/messages.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
Depends on https://github.com/HedvigInsurance/bot-service/pull/147
=> Add mutation for marking a message as read

src/schema.graphqls, src/typings/generated-graphql-types.ts
=> Let arranged peril categories be null.

src/api/index.ts, src/features/insurance/index.ts, src/schema.graphqls, src/schema.ts, src/typings/generated-graphql-types.ts
Also added added startup logging for AppContentService
=> Add renewal certificates+dates to insurance schema

src/features/chat/transform.ts, src/schema.graphqls, src/schema.ts, src/typings/generated-graphql-types.ts
based on this: https://github.com/HedvigInsurance/bot-service/blob/2c7a4899f13b724960ed7797f10c9cf82fb01226/src/main/java/com/hedvig/botService/enteties/message/TextContentType.kt
=> Add TextContentType to MessageBodyText & MessageBodyNumber

.env.example, src/index.ts, src/schema.ts
+ Proxy embarks format.js endpoint so that we can remove embark from heroku
=> Add embark schema

src/api/index.ts, src/resolvers/index.ts, src/resolvers/member.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
Country code should be posted as  ISO 3166 alpha-2
=> update market mutation 

src/api/index.ts, src/resolvers/member.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
Referrals in the feature list. I stole @sampettersson amazing idea of checking if the member has been referred to in product and pricing. So no more checks are needed. If the user gets referrals in features list show referrals otherwise don't :)
=> added referrals to features

package.json, src/index.ts, yarn.lock
Issue with caching icons - seemed to be problem with giraffe, trying a new proxy library to see if that solves the issue.
=> change proxy library

src/schema.ts
Reverts HedvigInsurance/giraffe#718
=> Revert "Remove auth from app-content-service"

src/api/index.ts, src/features/auth/auth.ts, src/features/auth/index.ts, src/resolvers/index.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
I totally forgot about giraffe but this should enable danish auth
=> enable danish auth

src/schema.ts
Caveat: I can't run this service locally, and hence this is not properly tested
=> Actually forward headers

src/schema.graphqls, src/typings/generated-graphql-types.ts
Also run gen :slightly_smiling_face:
=> you can't deprecate types, input and enums

src/schema.ts
Not 100% sure if this will break any of our usages, but let's try it out in staging for a moment and see how it goes 🚀
=> Migrate to new GraphCMS v2

src/resolvers/cross-schema/index.ts
This change is a part of HVG-280 and is dependent on HedvigInsurance/product-pricing#679.
=> Remove `termsAndConditions` from `Contract` in cross-schema resolver.

src/resolvers/index.ts, src/resolvers/selfChange.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
JIRA ticket: [BFF-22]
[BFF-22]: https://hedvig.atlassian.net/browse/BFF-22
=> move SelfChangeEligibility to giraffe to place it more symmetrically with the mutation

src/api/httpClient.ts, src/api/index.ts, src/api/upstream.ts, src/api/upstreams/productPricing.ts, src/config.ts, src/context.ts, src/resolvers/selfChange.ts
- Fill out the real values of the `embarkStoryId` based on the market of the member
- This should not be hard-coded in the clients, but since it's very UI-centric, it makes sense to live here.
[BFF-22]: https://hedvig.atlassian.net/browse/BFF-22
=> perform embark story triaging based on the market of the member

.env.example, src/config.ts, src/resolvers/availableLocales.ts, src/resolvers/index.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
This is to be used so that we can activate new markets with giraffe config instead of releasing new app builds.
=> Add available locales

src/resolvers/cross-schema/index.ts, src/resolvers/cross-schema/quoteFaqs.ts
This PR makes fetching faqs a bit cleaner.
- Make it take a `Locale` instead of  `FaqWhereInput`
- Add it to `QuoteBundle` to signal that the FAQs are relating to quotes
=> Add FAQ to quoteBundle

src/translations/LocalizedStrings.test.ts, src/translations/LocalizedStrings.ts
- Read the correct files in the localized strings
- Add tests to verify it
- I failed to do it last time, and there were quite a few moving pieces so I missed trying it out
=> load localized strings from the files correctly

src/api/upstreams/productPricing.ts, src/resolvers/contracts.test.ts, src/resolvers/contracts.ts
=> real logic for upcoming renewal

src/resolvers/contracts.ts
Perhaps we should use some form of Date-formatting library, though?
`date-fns` is pretty good.
-
-
=> Fix date formatting for TerminatedTodayStatus

src/resolvers/addressChange.test.ts, src/resolvers/addressChange.ts, src/resolvers/contracts.test.ts, src/resolvers/contracts.ts
Replacing ":" with "-" in `bundleId`
Since ":" is not a valid URL character we wont be able to parse it correctly when the id has been sent. This should fix that issue since "-" is a valid URL character.
=> Replace character in bundleId with a valid URL character

src/resolvers/contracts.ts
=> TerminatedTodayStatus fixed, but for real this time

src/resolvers/cross-schema/detailstable/tableRenderer.ts, src/resolvers/cross-schema/index.ts, src/resolvers/cross-schema/quoteBundleAppConfiguration.ts
- Add AppConfiguration to quote bundle
- Fix bug in details table renderer
- Moving flow needs this
=> Quote bundle app configuration

package.json, src/config.ts, src/utils/log.ts, yarn.lock
- Title says it all
- 'typescript-logging' that we were using looks like it's virtually unused and did not come with json logging
- https://www.npmtrends.com/log4js-vs-typescript-logging-vs-winston
=> Change to a more mature logging framework and use it to log in JSON for non-development

src/resolvers/cross-schema/index.ts, src/resolvers/cross-schema/quoteBundleOrderedQuotesExtension.ts
> Sorting QuoteBundle based on `typeOfContract`
> IPC needed help with this, and this is a feature request from App and Web clients.
[IPC-183]: https://hedvig.atlassian.net/browse/IPC-183
=> Sort QuoteBundle based on typeOfContract

src/resolvers/addressChange.test.ts, src/resolvers/addressChange.ts, src/schema.graphqls, src/typings/generated-graphql-types.ts
- add BRF to address change ownership enum 
- BRF != OWN, which the existing code incorrectly assumed
=> add BRF to address change ownership enum

src/resolvers/cross-schema/signOrApproveQuotes.ts
=> Fix extracting field not working for approveQuotes

src/resolvers/__snapshots__/contracts.test.ts.snap, src/resolvers/contracts.test.ts, src/test-utils/test-server.ts
- Rewrite the contracts tests to use snapshot testing and real GraphQL queries
- Using GraphQL for real means higher quality tests, and they are easier to maintain.
- I wanted to make sure there's a precedent for how we write tests in Giraffe
=> Move contracts, activeContractBundles query tests to snapshot testing instead, using real queries
